
global:
  scrape_interval: 5s
  scrape_timeout: 3s

scrape_configs:
  - job_name: 'mysql'
    scrape_interval: 5s
    static_configs:
      - targets: ['mysql-exporter:9104']
        labels:
          instance: mysql

